import { StyleSheet } from "react-native";
import { colors } from "../../constants/colors";
import { RFPercentage } from "react-native-responsive-fontsize";

export const styles = StyleSheet.create({
  appliedFiltersContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 16,
    marginLeft: 15,
  },
  filterTag: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.lightPurple,
    borderRadius: 25,
    paddingHorizontal: 16,
    paddingVertical: 6,
    marginRight: 8,
    marginBottom: 8,
  },
  errorText: {
    fontFamily: "Poppins-SemiBold",
    fontSize: RFPercentage(2.5),
    color: "red",
    alignSelf: "center",
    marginTop: RFPercentage(50),
  },
  selectedFilter: {
    color: colors.primary,
    fontFamily: "Poppins-Medium",
    fontSize: 12,
  },
  crossIcon: {
    fontSize: 16,
    color: colors.primary,
    marginLeft: 10,
  },
  label: {
    marginBottom: 12,
    fontFamily: "Poppins-SemiBold",
    color: colors.dark,
    fontSize: 14,
    marginTop: RFPercentage(0.6),
  },
  filterCenter: {
    height: 8,
    width: 60,
    borderRadius: 20,
    backgroundColor: colors.dimSecondary,
  },
  heading: {
    fontSize: 22,
    fontFamily: "Poppins-SemiBold",
    color: colors.dark,
  },
  outerContainer: {
    flex: 1,
    backgroundColor: "white",
  },
  container: {
    paddingVertical: RFPercentage(4),
  },
  headingContainer: {
    paddingHorizontal: 15,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  icon: {
    borderColor: colors.gray,
    borderWidth: 1,
    height: 40,
    width: 40,
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
  },
  searchContainer: {
    flexDirection: "row",
    borderColor: colors.gray,
    borderWidth: 0.5,
    borderRadius: 26,
    paddingHorizontal: RFPercentage(1),
    marginBottom: 23,
    height: 52,
    alignItems: "center",
    marginTop: 30,
    marginHorizontal: 15,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: colors.dark,
    paddingRight: RFPercentage(2),
    paddingTop: 12,
  },
  searchIcon: {
    paddingHorizontal: 8,
  },
  onGoingEventsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    marginBottom: 20,
    marginTop: 30,
  },
  goingEventText: {
    fontSize: 18,
    fontFamily: "Poppins-SemiBold",
    color: colors.dark,
  },
  seeAllText: {
    fontSize: 14,
    fontFamily: "Poppins-Medium",
    color: colors.primary,
  },
  cardContainer: {
    backgroundColor: "white",
    borderRadius: 16,
    shadowColor: colors.secondary,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.001,
    shadowRadius: 50,
    elevation: 7,
    padding: RFPercentage(1),
    marginVertical: 9,
    marginHorizontal: 15,
  },
  cardImage: {
    width: "100%",
    height: 160,
    borderRadius: 16,
    marginBottom: 16,
  },
  badgeContainer: {
    position: "absolute",
    top: 12,
    left: 12,
    backgroundColor: "white",
    height: 32,
    paddingHorizontal: 12,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  badgeText: {
    fontSize: 12,
    fontFamily: "Poppins-Medium",
    color: colors.dark,
  },
  cardHeading: {
    fontSize: 14,
    fontFamily: "Poppins-SemiBold",
    color: colors.dark,
    marginBottom: 8,
  },
  cardInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  creatorInfo: {
    flexDirection: "row",
    alignItems: "center",
  },
  creatorImage: {
    width: 18,
    height: 18,
    borderRadius: 25,
    marginRight: 8,
  },
  cardBody: {
    paddingHorizontal: RFPercentage(1),
  },
  creatorName: {
    fontSize: 12,
    fontFamily: "Poppins-Regular",
    color: colors.dark,
  },
  horizontalLine: {
    borderBottomColor: colors.gray,
    borderBottomWidth: 1,
    marginVertical: 16,
  },
  eventDate: {
    fontSize: 12,
    fontFamily: "Poppins-Regular",
    color: colors.secondary,
    paddingBottom: RFPercentage(1),
  },
  horizontalCardContainer: {
    flexDirection: "row",
    backgroundColor: "white",
    borderRadius: 25,
    shadowColor: colors.shadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 30,
    padding: RFPercentage(1),
    marginBottom: RFPercentage(3),
  },
  loaderContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
  },
  horizontalCardImage: {
    width: RFPercentage(15),
    height: RFPercentage(15),
    borderRadius: 25,
    marginRight: RFPercentage(2),
  },
  horizontalCardBody: {
    flex: 1,
    justifyContent: "center",
  },
  horizontalCardInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: RFPercentage(1),
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: colors.dimGray,
  },
  modalContent: {
    backgroundColor: "white",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingVertical: RFPercentage(2),
    paddingHorizontal: 24,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: RFPercentage(2),
  },
  filterHeading: {
    fontSize: 18,
    fontFamily: "Poppins-SemiBold",
    color: colors.dark,
  },
  resetButton: {
    fontSize: 14,
    fontFamily: "Poppins-Medium",
    color: colors.primary,
  },
  priceRangeContainer: {
    marginTop: 30,
    marginBottom: RFPercentage(2),
  },
  filterLabel: {
    fontSize: 14,
    color: colors.dark,
    fontFamily: "Poppins-Regular",
  },
  priceRange: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: RFPercentage(1),
  },
  priceOption: {
    padding: RFPercentage(1),
    borderRadius: 15,
    borderWidth: 1,
    borderColor: colors.gray,
    minWidth: RFPercentage(7),
    alignItems: "center",
  },
  selectedPriceOption: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  priceOptionText: {
    fontSize: 14,
    fontFamily: "Poppins-Regular",
    color: colors.dark,
  },
  selectedPriceOptionText: {
    color: "white",
  },
  datePickerButton: {
    borderRadius: 26,
    height: 52,
    justifyContent: "center",
    paddingHorizontal: 16,
    backgroundColor: colors.light,
    marginBottom: 16,
  },
  dropdownButton: {
    height: 52,
    backgroundColor: colors.light,
    borderRadius: 26,
    paddingHorizontal: 20,
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
  },
  dropdownContainer: {
    backgroundColor: "white",
    borderRadius: 15,
    borderWidth: 0.5,
    borderColor: colors.gray,
    maxHeight: RFPercentage(20),
    marginTop: RFPercentage(1),
  },
  dropdownItem: {
    padding: RFPercentage(1),
  },
  dropdownItemText: {
    fontSize: 13,
    fontFamily: "Poppins-Regular",
    color: colors.dark,
  },
  showResultsButton: {
    backgroundColor: colors.primary,
    borderRadius: 28,
    height: 52,
    alignItems: "center",
    justifyContent: "center",
    marginTop: RFPercentage(3),
  },
  showResultsButtonText: {
    fontSize: 14,
    fontFamily: "Poppins-SemiBold",
    color: "white",
  },
  horizontalOtherEventCardContainer: {
    flexDirection: "row",
    backgroundColor: "white",
    borderRadius: 16,
    shadowColor: colors.secondary,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 10,
    padding: RFPercentage(1),
    marginVertical: 9,
    width: "93%",
    alignSelf: "center",
  },
  horizontalOtherEventCardImage: {
    width: 88,
    height: 88,
    borderRadius: 12,
    marginRight: 12,
  },
  horizontalOtherEventCardBody: {
    flex: 1,
    justifyContent: "center",
  },
  horizontalOtherEventCardInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  otherEventBadgeText: {
    fontSize: 12,
    fontFamily: "Poppins-Regular",
    color: colors.secondary,
  },
  otherEventCardHeading: {
    fontSize: 14,
    fontFamily: "Poppins-SemiBold",
    color: colors.dark,
  },
  otherEventDate: {
    fontSize: 12,
    fontFamily: "Poppins-Regular",
    color: colors.secondary,
  },
});
